version: '3.9'

services:
  sgu-prae-service:
    image: sgu-prae-service
    build: .
    ports:
      - "8082:8082"
    container_name: sgu-prae-service
    networks:
      - sgu-networks
    environment:
      TZ: America/Sao_Paulo
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      prae-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      keycloak: # <-- PRAE agora espera o Keycloak
        condition: service_healthy
    volumes:
      - ./storage:/app/storage

  prae-db:
    image: postgres:16.0
    restart: always
    container_name: prae-db
    environment:
      POSTGRES_DB: prae
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prae"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5435:5432"
    networks:
      - sgu-networks
    volumes:
      - pg-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sgu-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sgu-networks

  redis:
    image: redis:7-alpine
    container_name: sgu-redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - sgu-networks
    volumes:
      - redis-data:/data

  keycloak: # <-- Novo bloco do Keycloak adicionado
    image: quay.io/keycloak/keycloak:26.0.4
    container_name: sgu-keycloak
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    ports:
      - "9090:8080" # Porta 9090 mapeada externamente para bater com o application.yml
    command: start-dev # Roda em modo de desenvolvimento (ideal para testes locais)
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/9000'" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - sgu-networks
    # volumes: <-- Descomentar isso para importar o Realm automático
    #   - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

volumes:
  pg-data:
    driver: local
  redis-data:
    driver: local

networks:
  sgu-networks: