-- =================================================================================
-- V1: Baseline Inicial do Sistema
-- =================================================================================

-- 1. TABELAS DE DOMÍNIO AUXILIAR
CREATE TABLE tipo_etnia (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            tipo VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE curso (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       ativo BOOLEAN NOT NULL DEFAULT TRUE,
                       nome VARCHAR(255) UNIQUE,
                       numero_periodos INTEGER NOT NULL
);

CREATE TABLE tipo_atendimento (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  nome VARCHAR(255),
                                  tempo_atendimento TIME WITHOUT TIME ZONE
);

CREATE TABLE tipo_atendimento_horarios (
                                           tipo_atendimento_id BIGINT NOT NULL REFERENCES tipo_atendimento(id),
                                           horarios TIME WITHOUT TIME ZONE
);

CREATE TABLE tipo_beneficio (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ativo BOOLEAN NOT NULL,
                                descricao VARCHAR(255),
                                natureza_beneficio SMALLINT,
                                tipo VARCHAR(255),
                                valor_beneficio NUMERIC(38,2)
);

CREATE TABLE dados_bancarios (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 agencia VARCHAR(255),
                                 banco VARCHAR(255),
                                 conta VARCHAR(255),
                                 nome_titular VARCHAR(255),
                                 tipo_conta VARCHAR(255)
);

CREATE TABLE endereco (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          bairro VARCHAR(255),
                          cep VARCHAR(255),
                          cidade VARCHAR(255),
                          complemento VARCHAR(255),
                          estado VARCHAR(255),
                          numero VARCHAR(255),
                          rua VARCHAR(255)
);

-- 2. TABELAS DE IDENTIDADE E HERANÇA (USUÁRIOS)
CREATE TABLE usuario (
                         id UUID PRIMARY KEY,
                         ativo BOOLEAN NOT NULL DEFAULT TRUE,
                         cpf VARCHAR(255) UNIQUE NOT NULL,
                         email VARCHAR(255) UNIQUE NOT NULL,
                         nome VARCHAR(255),
                         nome_social VARCHAR(255),
                         telefone VARCHAR(255),
                         tipo_etnia_id BIGINT REFERENCES tipo_etnia(id)
);

CREATE TABLE estudante (
                           id UUID PRIMARY KEY REFERENCES usuario(id),
                           contato_familia VARCHAR(255),
                           deficiente BOOLEAN NOT NULL,
                           renda_percapta NUMERIC(38,2),
                           tipo_deficiencia VARCHAR(255),
                           matricula VARCHAR(255) UNIQUE,
                           curso_id BIGINT REFERENCES curso(id),
                           dados_bancarios_id BIGINT UNIQUE REFERENCES dados_bancarios(id),
                           endereco_id BIGINT UNIQUE REFERENCES endereco(id)
);

CREATE TABLE profissional (
                              id UUID PRIMARY KEY REFERENCES usuario(id),
                              especialidade VARCHAR(255) NOT NULL,
                              siape VARCHAR(255)
);

CREATE TABLE gestor (
                        id UUID PRIMARY KEY REFERENCES usuario(id),
                        siape VARCHAR(255)
);

-- 3. TABELAS OPERACIONAIS (PRAE)
CREATE TABLE documento (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nome VARCHAR(255),
                           path VARCHAR(255),
                           estudante_id UUID REFERENCES estudante(id)
);

CREATE TABLE cronograma (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ativo BOOLEAN NOT NULL,
                            data DATE NOT NULL,
                            profissional_id UUID REFERENCES profissional(id),
                            tipo_atendimento_id BIGINT REFERENCES tipo_atendimento(id)
);

CREATE TABLE vaga (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      disponivel BOOLEAN NOT NULL,
                      hora_fim TIME WITHOUT TIME ZONE,
                      hora_inicio TIME WITHOUT TIME ZONE,
                      version BIGINT,
                      cronograma_id BIGINT REFERENCES cronograma(id)
);

CREATE TABLE agendamento (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             ativo BOOLEAN NOT NULL,
                             confirmacao_enviada BOOLEAN NOT NULL DEFAULT FALSE,
                             data DATE NOT NULL,
                             data_criacao TIMESTAMP(6) WITHOUT TIME ZONE,
                             modalidade VARCHAR(255) NOT NULL,
                             estudante_id UUID REFERENCES estudante(id),
                             vaga_id BIGINT REFERENCES vaga(id)
);

CREATE TABLE cancelamento_agendamento (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          data_cancelamento TIMESTAMP(6) WITHOUT TIME ZONE,
                                          motivo VARCHAR(255),
                                          agendamento_id BIGINT NOT NULL UNIQUE REFERENCES agendamento(id)
);

CREATE TABLE beneficio (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           ativo BOOLEAN NOT NULL,
                           fim_beneficio DATE,
                           inicio_beneficio DATE,
                           motivo_encerramento VARCHAR(255),
                           observacao_prorrogacao VARCHAR(500),
                           parecer_termino VARCHAR(255),
                           status BOOLEAN NOT NULL,
                           valor_pagamento NUMERIC(38,2),
                           estudantes_id UUID REFERENCES estudante(id),
                           termo_id BIGINT UNIQUE REFERENCES documento(id),
                           tipo_beneficio_id BIGINT REFERENCES tipo_beneficio(id)
);

CREATE TABLE pagamento (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           ano_referencia INTEGER,
                           ativo BOOLEAN NOT NULL,
                           data DATE,
                           mes_referencia INTEGER,
                           numero_lote VARCHAR(255),
                           valor NUMERIC(38,2),
                           beneficio_id BIGINT REFERENCES beneficio(id)
);