-- =================================================================================
-- V1: Baseline Inicial do Sistema
-- =================================================================================

-- 1. TABELAS INDEPENDENTES
CREATE TABLE dados_bancarios (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 agencia VARCHAR(255),
                                 banco VARCHAR(255),
                                 conta VARCHAR(255),
                                 nome_titular VARCHAR(255),
                                 tipo_conta VARCHAR(255)
);

CREATE TABLE endereco (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          bairro VARCHAR(255),
                          cep VARCHAR(255),
                          cidade VARCHAR(255),
                          complemento VARCHAR(255),
                          estado VARCHAR(255),
                          numero VARCHAR(255),
                          rua VARCHAR(255)
);

CREATE TABLE profissional (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              ativo BOOLEAN,
                              especialidade VARCHAR(255) NOT NULL,
                              user_id UUID NOT NULL UNIQUE
);

CREATE TABLE tipo_atendimento (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  nome VARCHAR(255),
                                  tempo_atendimento TIME
);

CREATE TABLE tipo_beneficio (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ativo BOOLEAN NOT NULL,
                                descricao VARCHAR(255),
                                natureza_beneficio SMALLINT, -- Enum sem anotação STRING é salvo como inteiro
                                tipo VARCHAR(255),
                                valor_beneficio NUMERIC(38,2)
);

-- 2. TABELAS BASE (Com dependências das anteriores)
CREATE TABLE estudante (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           ativo BOOLEAN NOT NULL,
                           contato_familia VARCHAR(255),
                           deficiente BOOLEAN NOT NULL,
                           renda_percapta NUMERIC(38,2),
                           tipo_deficiencia VARCHAR(255),
                           user_id UUID NOT NULL UNIQUE,
                           dados_bancarios_id BIGINT UNIQUE REFERENCES dados_bancarios(id), -- Garantia de OneToOne
                           endereco_id BIGINT UNIQUE REFERENCES endereco(id) -- Garantia de OneToOne
);

CREATE TABLE documento (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nome VARCHAR(255),
                           path VARCHAR(255),
                           user_id UUID,
                           estudante_id BIGINT REFERENCES estudante(id) -- Vem do @OneToMany com @JoinColumn
);

CREATE TABLE cronograma (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ativo BOOLEAN NOT NULL,
                            data DATE NOT NULL,
                            profissional_id BIGINT REFERENCES profissional(id),
                            tipo_atendimento_id BIGINT REFERENCES tipo_atendimento(id)
);

CREATE TABLE beneficio (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           ativo BOOLEAN NOT NULL,
                           fim_beneficio DATE,
                           inicio_beneficio DATE,
                           motivo_encerramento VARCHAR(255),
                           observacao_prorrogacao VARCHAR(500),
                           parecer_termino VARCHAR(255),
                           status BOOLEAN NOT NULL,
                           valor_pagamento NUMERIC(38,2),
                           estudantes_id BIGINT REFERENCES estudante(id),
                           termo_id BIGINT UNIQUE REFERENCES documento(id), -- Garantia de OneToOne
                           tipo_beneficio_id BIGINT REFERENCES tipo_beneficio(id)
);

-- 3. TABELAS COM MÚLTIPLAS DEPENDÊNCIAS
CREATE TABLE pagamento (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           ano_referencia INTEGER,
                           ativo BOOLEAN NOT NULL,
                           data DATE,
                           mes_referencia INTEGER,
                           numero_lote VARCHAR(255),
                           valor NUMERIC(38,2),
                           beneficio_id BIGINT REFERENCES beneficio(id)
);

CREATE TABLE vaga (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      disponivel BOOLEAN NOT NULL,
                      hora_fim TIME,
                      hora_inicio TIME,
                      version BIGINT, -- Usado pelo @Version (Optimistic Locking)
                      cronograma_id BIGINT REFERENCES cronograma(id)
);

CREATE TABLE agendamento (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             ativo BOOLEAN NOT NULL,
                             data DATE NOT NULL,
                             data_criacao TIMESTAMP(6) WITHOUT TIME ZONE,
                             modalidade VARCHAR(255) NOT NULL,
                             estudante_id BIGINT REFERENCES estudante(id),
                             vaga_id BIGINT REFERENCES vaga(id)
);

CREATE TABLE cancelamento_agendamento (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          data_cancelamento TIMESTAMP(6) WITHOUT TIME ZONE,
                                          motivo VARCHAR(255),
                                          agendamento_id BIGINT NOT NULL UNIQUE REFERENCES agendamento(id)
);

-- 4. TABELA DE COLEÇÃO (ElementCollection)
CREATE TABLE tipo_atendimento_horarios (
                                           tipo_atendimento_id BIGINT NOT NULL REFERENCES tipo_atendimento(id),
                                           horarios TIME
);