-- =================================================================================
-- V3: Migração de Identidade e Herança Modular
-- =================================================================================

-- 1. Tabelas Auxiliares (Base Auth)
CREATE TABLE tipo_etnia (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            tipo VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE curso (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       ativo BOOLEAN NOT NULL DEFAULT TRUE,
                       nome VARCHAR(255) UNIQUE,
                       numero_periodos INTEGER NOT NULL
);

-- 2. Tabela Pai (Herança JOINED)
CREATE TABLE usuario (
                         id UUID PRIMARY KEY,
                         ativo BOOLEAN NOT NULL DEFAULT TRUE,
                         cpf VARCHAR(255) UNIQUE NOT NULL,
                         email VARCHAR(255) UNIQUE NOT NULL,
                         nome VARCHAR(255),
                         nome_social VARCHAR(255),
                         telefone VARCHAR(255),
                         tipo_etnia_id BIGINT REFERENCES tipo_etnia(id)
);

-- 3. Migração da Entidade Estudante
ALTER TABLE estudante ADD COLUMN matricula VARCHAR(255) UNIQUE;
ALTER TABLE estudante ADD COLUMN curso_id BIGINT REFERENCES curso(id);

-- 3.1 Substituindo as FKs BIGINT por UUID nas tabelas que dependem do Estudante
ALTER TABLE agendamento ADD COLUMN estudante_uuid UUID;
UPDATE agendamento SET estudante_uuid = (SELECT user_id FROM estudante WHERE id = agendamento.estudante_id);
ALTER TABLE agendamento DROP COLUMN estudante_id CASCADE;
ALTER TABLE agendamento RENAME COLUMN estudante_uuid TO estudante_id;

ALTER TABLE beneficio ADD COLUMN estudante_uuid UUID;
UPDATE beneficio SET estudante_uuid = (SELECT user_id FROM estudante WHERE id = beneficio.estudantes_id);
ALTER TABLE beneficio DROP COLUMN estudantes_id CASCADE;
ALTER TABLE beneficio RENAME COLUMN estudante_uuid TO estudantes_id;

ALTER TABLE documento ADD COLUMN estudante_uuid UUID;
UPDATE documento SET estudante_uuid = (SELECT user_id FROM estudante WHERE id = documento.estudante_id);
ALTER TABLE documento DROP COLUMN estudante_id CASCADE;
ALTER TABLE documento RENAME COLUMN estudante_uuid TO estudante_id;

-- 3.2 Ascensão do user_id à Primary Key
ALTER TABLE estudante DROP CONSTRAINT IF EXISTS estudante_pkey CASCADE;
ALTER TABLE estudante DROP COLUMN id CASCADE;
ALTER TABLE estudante RENAME COLUMN user_id TO id;
ALTER TABLE estudante ADD PRIMARY KEY (id);
ALTER TABLE estudante ADD CONSTRAINT fk_estudante_usuario FOREIGN KEY (id) REFERENCES usuario(id);

-- 3.3 Religar restrições estrangeiras
ALTER TABLE agendamento ADD CONSTRAINT fk_agendamento_estudante FOREIGN KEY (estudante_id) REFERENCES estudante(id);
ALTER TABLE beneficio ADD CONSTRAINT fk_beneficio_estudante FOREIGN KEY (estudantes_id) REFERENCES estudante(id);
ALTER TABLE documento ADD CONSTRAINT fk_documento_estudante FOREIGN KEY (estudante_id) REFERENCES estudante(id);


-- 4. Migração da Entidade Profissional
ALTER TABLE profissional ADD COLUMN siape VARCHAR(255);

-- 4.1 Substituindo FKs BIGINT por UUID
ALTER TABLE cronograma ADD COLUMN profissional_uuid UUID;
UPDATE cronograma SET profissional_uuid = (SELECT user_id FROM profissional WHERE id = cronograma.profissional_id);
ALTER TABLE cronograma DROP COLUMN profissional_id CASCADE;
ALTER TABLE cronograma RENAME COLUMN profissional_uuid TO profissional_id;

-- 4.2 Ascensão do user_id à Primary Key
ALTER TABLE profissional DROP CONSTRAINT IF EXISTS profissional_pkey CASCADE;
ALTER TABLE profissional DROP COLUMN id CASCADE;
ALTER TABLE profissional RENAME COLUMN user_id TO id;
ALTER TABLE profissional ADD PRIMARY KEY (id);
ALTER TABLE profissional ADD CONSTRAINT fk_profissional_usuario FOREIGN KEY (id) REFERENCES usuario(id);

-- 4.3 Religar restrição estrangeira
ALTER TABLE cronograma ADD CONSTRAINT fk_cronograma_profissional FOREIGN KEY (profissional_id) REFERENCES profissional(id);


-- 5. Criação da tabela Gestor
CREATE TABLE gestor (
                        id UUID PRIMARY KEY REFERENCES usuario(id),
                        siape VARCHAR(255)
);